# Generated by Django 5.0.3 on 2024-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_productive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biblioteca",
            name="archivo",
            field=models.FileField(upload_to=""),
        ),
    ]
