# Generated by Django 5.0.3 on 2024-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_productive", "0002_alter_biblioteca_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwords",
            name="contrasena",
            field=models.CharField(max_length=500),
        ),
    ]
